servicios:
- nombre: Desarrollo de Software
  icono : fas fa-code
- nombre: Desarrollo Web
  icono : fas fa-desktop
- nombre: Soluciones Tecnológicas
  icono : fas fa-code-branch
- nombre: Healthtech
  icono : fas fa-laptop-medical
- nombre: Fintech
  icono : fas fa-hand-holding-usd
- nombre: E-commerce
  icono : fas fa-shopping-basket
- nombre: Desarrollo a la medida
  icono : fas fa-pencil-ruler
- nombre: Facturación electrónica
  icono : fas fa-file-invoice-dollar
- nombre: Staffing
  icono : fas fa-user-check
- nombre: Software as a Service
  icono : fas fa-laptop-code
- nombre: Monitoreo de SW & HW
  icono : fas fa-chart-bar
- nombre: Consultoría TIC
  icono : fas fa-users-cog
- nombre: Asesoría en propiedad intelectual en temas de tecnología
  icono : far fa-newspaper
- nombre: Tratamiento de imagen
  icono : far fa-check-square
- nombre: Servicios de telecomunicaciones
  icono : fas fa-network-wired
- nombre: Uso de PLC
  icono : fas fa-tools
- nombre: Redes industriales
  icono : fas fa-share-alt
- nombre: Realidad aumentada
  icono : far fa-eye
- nombre: 3D Printing
  icono : fas fa-print
- nombre: Business Intelligence
  icono : fas fa-funnel-dollar
- nombre: Big data y Analítica de datos
  icono : fas fa-chart-pie
- nombre: Inteligencia artificial
  icono : fas fa-project-diagram
- nombre: Robótica
  icono : fas fa-robot
- nombre: IoT
  icono : fas fa-globe
- nombre: Ciberseguridad
  icono : fas fa-lock
- nombre: Blockchain
  icono : fas fa-sitemap
- nombre: Nube
  icono : fas fa-cloud