servicios:
- nombre: Desarrollo de Software
  icono : software-development-icon.svg
- nombre: Desarrollo Web
  icono : web-page-icon.svg
- nombre: Soluciones Tecnológicas
  icono : creative-idea-solution-icon.svg
- nombre: Healthtech
  icono : health-and-safety-icon.svg
- nombre: Fintech
  icono : fintech-icon.svg
- nombre: E-commerce
  icono : e-commerce-shopping-website-icon.svg
- nombre: Desarrollo a la medida
  icono : setting-computer-desktop-icon.svg
- nombre: Facturación electrónica
  icono : checkmark-invoice-icon.svg
- nombre: Staffing
  icono : corporate-icon.svg
- nombre: Software as a Service
  icono : saas-icon.svg
- nombre: Monitoreo de SW & HW
  icono : monitoring-system-icon.svg
- nombre: Consultoría TIC
  icono : comments-icon.svg
- nombre: Asesoría en propiedad intelectual en temas de tecnología
  icono : copyright-content-icon.svg
- nombre: Tratamiento de imagen
  icono : add-image-photo-icon.svg
- nombre: Servicios de telecomunicaciones
  icono : base-station-icon.svg
- nombre: Uso de PLC
  icono : tools-icon.svg
- nombre: Redes industriales
  icono : share-square-line-icon.svg
- nombre: Realidad aumentada
  icono : virtual-world-icon.svg
- nombre: 3D Printing
  icono : 3d-printing-icon.svg
- nombre: Business Intelligence
  icono : business-man-investor-dollar-icon.svg
- nombre: Big data y Analítica de datos
  icono : data-sheet-icon.svg
- nombre: Inteligencia artificial
  icono : artificial-intelligence-ai-icon.svg
- nombre: Robótica
  icono : mechanical-arm-icon.svg
- nombre: IoT
  icono : smart-city-icon.svg
- nombre: Ciberseguridad
  icono : encrypted-icon.svg
- nombre: Blockchain
  icono : blockchain-development-icon.svg
- nombre: Nube
  icono : cloud-backup-icon.svg
