servicios:
- nombre: Desarrollo de Software
  icono : placeholder.svg
- nombre: Desarrollo Web
  icono : placeholder.svg
- nombre: Soluciones Tecnológicas
  icono : placeholder.svg
- nombre: Healthtech
  icono : placeholder.svg
- nombre: Fintech
  icono : placeholder.svg
- nombre: E-commerce
  icono : placeholder.svg
- nombre: Desarrollo a la medida
  icono : placeholder.svg
- nombre: Facturación electrónica
  icono : placeholder.svg
- nombre: Staffing
  icono : placeholder.svg
- nombre: Software as a Service
  icono : placeholder.svg
- nombre: Monitoreo de SW & HW
  icono : placeholder.svg
- nombre: Consultoría TIC
  icono : placeholder.svg
- nombre: Asesoría en propiedad intelectual en temas de tecnología
  icono : placeholder.svg
- nombre: Tratamiento de imagen
  icono : placeholder.svg
- nombre: Servicios de telecomunicaciones
  icono : placeholder.svg
- nombre: Uso de PLC
  icono : placeholder.svg
- nombre: Redes industriales
  icono : placeholder.svg
- nombre: Realidad aumentada
  icono : placeholder.svg
- nombre: 3D Printing
  icono : placeholder.svg
- nombre: Business Intelligence
  icono : placeholder.svg
- nombre: Big data y Analítica de datos
  icono : placeholder.svg
- nombre: Inteligencia artificial
  icono : placeholder.svg
- nombre: Robótica
  icono : placeholder.svg
- nombre: IoT
  icono : placeholder.svg
- nombre: Ciberseguridad
  icono : placeholder.svg
- nombre: Blockchain
  icono : placeholder.svg
- nombre: Nube
  icono : placeholder.svg
